---

- name: ensure a list of packages installed
  yum:
    name: "{{ packages }}"
  vars:
    packages:
    - python-setuptools
    - python-pip


# TODO: Change this for python36
#- name: "Install pip package"
#  shell: |
#    curl "https://bootstrap.pypa.io/get-pip.py" -o "get-pip.py" && \
#    python get-pip.py --user
#
- name: Install Docker Module for Python
  pip:
    name: docker
