---
- name: - name: "{{ ansible_distribution | lower }} | {{ ansible_distribution_release }} - Ensure old versions of Docker are not installed."
  package:
    name:
      - docker
      - docker-common
      - docker-engine
    state: absent

- name: "{{ ansible_distribution | lower }} | {{ ansible_distribution_release }} - Ensure old versions of Docker are not installed."
  package:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg2
      - software-properties-common

- name: "{{ ansible_distribution | lower }} | {{ ansible_distribution_release }} - Add Docker GPG key."
  apt-key:
    key: https://download.docker.com/linux/debian/gpg
    state: present

- name: Ensure curl is present (on older systems without SNI).
  package: name=curl state=present
  when: add_repository_key is failed

- name: Add Docker apt key (alternative for older systems without SNI).
  shell: |
    set -o pipefail
    curl -sSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  args:
    warn: false
  when: add_repository_key is failed

- name: "{{ ansible_distribution | lower }} | {{ ansible_distribution_release }} - Add Docker repository."
  apt_repository:
    repo: "{{ docker_apt_repository }}"
    state: present
    update_cache: true